version: '3.7'

services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8010
    volumes:
      - ./src:/home/app/web/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A core worker --loglevel=info --uid=nobody
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  nginx:
    container_name: nginx
    build:
      context: nginx/
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - "8080:80"
    depends_on:
      - web

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=navisdevs
      - POSTGRES_PASSWORD=adminadmin
      - POSTGRES_DB=businesskg
    depends_on:
      - redis

volumes:
  static_volume:
  media_volume:
  postgres_data:
